local O0O0O0O=loadstring(game:HttpGet("\104\116\116\112\115\58\47\47\115\105\114\105\117\115\46\109\101\110\117\47\114\97\121\102\105\101\108\100"))()
local I1I1lOl=O0O0O0O:CreateWindow({
    Name="\226\128\186Eli And Sen Muscle Legend\226\128\186",
    Icon=0,
    LoadingTitle="\226\128\186Eli And Sen Muscle Legend\226\128\186 v1",
    LoadingSubtitle="by Eli And Sen",
    Theme="Bloom",
    ToggleUIKeybind="K",
    DisableRayfieldPrompts=false,
    DisableBuildWarnings=false,
    ConfigurationSaving={Enabled=true,FolderName=nil,FileName="Big Hub"},
    Discord={Enabled=false,Invite="noinvitelink",RememberJoins=true},
    KeySystem=true,
    KeySettings={
        Title="Eli Key System",
        Subtitle="Key System",
        Note="OBTAIN THE KEY IN MY GITHUB RESPIRATORY!!",
        FileName="Key",
        SaveKey=false,
        GrabKeyFromSite=true,
        Key={"https://raw.githubusercontent.com/SCRIPTDEVELOPERzzzz/SLH-Eli/refs/heads/main/Key"}
    }
})
local OOo0O0O=I1I1lOl:CreateTab("Farm",4483362458)local l1IlI1l=I1I1lOl:CreateTab("ToolsAndRock",4483362458)local Il1lI0O=I1I1lOl:CreateTab("Eggies",4483362458)local l0l01lO=I1I1lOl:CreateTab("Teleport+++(+)",4483362458)local O01Il1I=I1I1lOl:CreateTab("KillerX",4483362458)local I0O1lO1=I1I1lOl:CreateTab("MorningNightDay",4483362458)local l0O0lO1=I1I1lOl:CreateTab("CreditsZ",4483362458)local lO10l1O=game.Players.LocalPlayer
local O0Ol0O0={Weight=false,Pushups=false,Situps=false,Handstands=false}local O0OlI1O={}local lOl1I0O={}local function oL0l10O(o)O0Ol0O0[o]=false end;local function I1O0lO1(t,f)O0Ol0O0[t]=true;O0OlI1O[t]=coroutine.create(function()while O0Ol0O0[t]do for _,v in pairs(lO10l1O.Backpack:GetChildren())do if v.ClassName=="Tool"and v.Name==f then v.Parent=lO10l1O.Character end end;lO10l1O.muscleEvent:FireServer("rep")wait(.1)end end)coroutine.resume(O0OlI1O[t])end
OOo0O0O:CreateSection("AutoLiftTools")OOo0O0O:CreateToggle({Name="Rep Weight (On/Off)",CurrentValue=false,Callback=function(s)if s then I1O0lO1("Weight","Weight")else oL0l10O("Weight")end end})OOo0O0O:CreateToggle({Name="Rep Pushups (On/Off)",CurrentValue=false,Callback=function(s)if s then I1O0lO1("Pushups","Pushups")else oL0l10O("Pushups")end end})OOo0O0O:CreateToggle({Name="Rep Situps (On/Off)",CurrentValue=false,Callback=function(s)if s then I1O0lO1("Situps","Situps")else oL0l10O("Situps")end end})OOo0O0O:CreateToggle({Name="Rep Handstands (On/Off)",CurrentValue=false,Callback=function(s)if s then I1O0lO1("Handstands","Handstands")else oL0l10O("Handstands")end end})OOo0O0O:CreateButton({Name="Start/Stop Auto Click (Equipped Tool)",Callback=function()if not _G.FarmTabAutoClick then _G.FarmTabAutoClick=true;O0O0O0O:Notify({Title="Auto Click",Content="Auto Click started. Press the button again to stop.",Duration=3})spawn(function()while _G.FarmTabAutoClick do local c=lO10l1O.Character;if c then for _,t in pairs(c:GetChildren())do if t.ClassName=="Tool"and t.Activate then if t:FindFirstChild("attackTime")then t.attackTime.Value=0 end;t:Activate()end end end;wait(.05)end end)else _G.FarmTabAutoClick=false;O0O0O0O:Notify({Title="Auto Click",Content="Auto Click stopped.",Duration=3})end end})
OOo0O0O:CreateSection("FarmRebirths")local O0O1O1I,O1lO0O0=false,false;local O0I0Ol1=0
OOo0O0O:CreateInput({Name="Set Rebirth Stop Point",PlaceholderText="Enter rebirths to stop at (number)",RemoveTextAfterFocusLost=false,Callback=function(V)O0I0Ol1=tonumber(V)or 0 end})OOo0O0O:CreateToggle({Name="Auto Rebirth (On/Off)",CurrentValue=false,Callback=function(S)O0O1O1I=S;while O0O1O1I do wait(.1)local l=lO10l1O:FindFirstChild("leaderstats")local x=l and l:FindFirstChild("Rebirths")if O0I0Ol1>0 and x and x.Value>=O0I0Ol1 then O0O1O1I=false;break end;game:GetService("ReplicatedStorage").rEvents.rebirthRemote:InvokeServer("rebirthRequest")end end})OOo0O0O:CreateToggle({Name="Auto Target Rebirth (On/Off)",CurrentValue=false,Callback=function(E)O1lO0O0=E;if not E then return end;local l=lO10l1O:FindFirstChild("leaderstats")local x=l and l:FindFirstChild("Rebirths")if not x or O0I0Ol1<=0 then O0O0O0O:Notify({Title="Auto Target Rebirth",Content="Please set a valid rebirth stop point and make sure Rebirths stat exists.",Duration=5})O1lO0O0=false;return end;spawn(function()while O1lO0O0 and x.Value<O0I0Ol1 do wait(.1)game:GetService("ReplicatedStorage").rEvents.rebirthRemote:InvokeServer("rebirthRequest")end;if O1lO0O0 and x.Value>=O0I0Ol1 then O0O0O0O:Notify({Title="Auto Target Rebirth",Content="Target rebirth reached!",Duration=5})end;O1lO0O0=false end)end})
OOo0O0O:CreateSection("FarmRocks")local o0l0lO={{name="Legend",durability=1000000,label="Legend Gym Rock"},{name="King",durability=5000000,label="Muscle King Gym Rock"},{name="Jungle",durability=10000000,label="Ancient Jungle Rock"},{name="TinyRock",durability=0,label="Tiny Rock"},{name="PunchingRock",durability=10,label="Punching Rock"},{name="LargeRock",durability=100,label="Large Rock"},{name="GoldenRock",durability=5000,label="Golden Rock"},{name="FrozenRock",durability=150000,label="Frozen Rock"},{name="MythicalRock",durability=400000,label="Mythical Rock"},{name="EternalRock",durability=750000,label="Eternal Rock"},}getgenv().autoFarmRocks=getgenv().autoFarmRocks or {}for _,v in ipairs(o0l0lO)do OOo0O0O:CreateToggle({Name=v.label.." (On/Off)",CurrentValue=false,Callback=function(Vu)getgenv().autoFarmRocks[v.name]=Vu;if Vu then task.spawn(function()while getgenv().autoFarmRocks[v.name]do task.wait(.1)if not getgenv().autoFarmRocks[v.name]then break end;if lO10l1O:FindFirstChild("Durability")and lO10l1O.Durability.Value>=v.durability then for _,a in pairs(game:GetService("Workspace").machinesFolder:GetDescendants())do if a.Name=="neededDurability"and a.Value==v.durability and lO10l1O.Character and lO10l1O.Character:FindFirstChild("LeftHand")and lO10l1O.Character:FindFirstChild("RightHand")then firetouchinterest(a.Parent.Rock,lO10l1O.Character.RightHand,0)firetouchinterest(a.Parent.Rock,lO10l1O.Character.RightHand,1)firetouchinterest(a.Parent.Rock,lO10l1O.Character.LeftHand,0)firetouchinterest(a.Parent.Rock,lO10l1O.Character.LeftHand,1)end end end end end)end end})end
OOo0O0O:CreateToggle({Name="Auto Fast Punch",CurrentValue=false,Flag="AutoFastPunch",Callback=function(Q)_G.fastHitActive=Q;if Q then coroutine.wrap(function()while _G.fastHitActive do local p=lO10l1O.Backpack:FindFirstChild("Punch")if p then p.Parent=lO10l1O.Character;if p:FindFirstChild("attackTime")then p.attackTime.Value=0 end end;wait()end end)()coroutine.wrap(function()while _G.fastHitActive do lO10l1O.muscleEvent:FireServer("punch","rightHand")lO10l1O.muscleEvent:FireServer("punch","leftHand")local c=lO10l1O.Character;if c then local t=c:FindFirstChild("Punch")if t then t:Activate()end end;wait()end end)()coroutine.wrap(function()while _G.fastHitActive do lO10l1O.muscleEvent:FireServer("rep")wait()end end)()else local c=lO10l1O.Character;local e=c and c:FindFirstChild("Punch")if e then e.Parent=lO10l1O.Backpack end end end})
local function o1OIlO0(t,f)if not getgenv().comboToggles then getgenv().comboToggles={}end;local k=t.."_Ancient"if getgenv().comboToggles[k]then return end;getgenv().comboToggles[k]=true;spawn(function()while getgenv().comboToggles[k]do for _,v in pairs(lO10l1O.Backpack:GetChildren())do if v.ClassName=="Tool"and v.Name==f then v.Parent=lO10l1O.Character end end;lO10l1O.muscleEvent:FireServer("rep")lO10l1O.muscleEvent:FireServer("punch","rightHand")lO10l1O.muscleEvent:FireServer("punch","leftHand")local c=lO10l1O.Character;if c then local t=c:FindFirstChild("Punch")if t then t:Activate()end end;for _,a in pairs(game:GetService("Workspace").machinesFolder:GetDescendants())do if a.Name=="neededDurability"and a.Value==10000000 and lO10l1O.Character and lO10l1O.Character:FindFirstChild("LeftHand")and lO10l1O.Character:FindFirstChild("RightHand")then firetouchinterest(a.Parent.Rock,lO10l1O.Character.RightHand,0)firetouchinterest(a.Parent.Rock,lO10l1O.Character.RightHand,1)firetouchinterest(a.Parent.Rock,lO10l1O.Character.LeftHand,0)firetouchinterest(a.Parent.Rock,lO10l1O.Character.LeftHand,1)end end;wait(.15)end end)end;local function O1lO0Ol(t)if getgenv().comboToggles then local k=t.."_Ancient"getgenv().comboToggles[k]=false end end
l1IlI1l:CreateToggle({Name="Auto Weight + Auto Punch Ancient Rock",CurrentValue=false,Callback=function(V)if V then o1OIlO0("Weight","Weight")else O1lO0Ol("Weight")end end})l1IlI1l:CreateToggle({Name="Auto Pushups + Auto Punch Ancient Rock",CurrentValue=false,Callback=function(V)if V then o1OIlO0("Pushups","Pushups")else O1lO0Ol("Pushups")end end})l1IlI1l:CreateToggle({Name="Auto Situps + Auto Punch Ancient Rock",CurrentValue=false,Callback=function(V)if V then o1OIlO0("Situps","Situps")else O1lO0Ol("Situps")end end})l1IlI1l:CreateToggle({Name="Auto Handstand + Auto Punch Ancient Rock",CurrentValue=false,Callback=function(V)if V then o1OIlO0("Handstands","Handstands")else O1lO0Ol("Handstands")end end})
local oollO0={"Blue Crystal","Green Crystal","Mythical Crystal","Frost Crystal","Inferno Crystal","Legends Crystal","Muscle Elite Crystal","Jungle Crystal"}local l1O1O0=oollO0[1]Il1lI0O:CreateDropdown({Name="Select Crystal",Options=oollO0,CurrentOption=l1O1O0,Callback=function(i)l1O1O0=i end})local O0O0oO0,O0O0O01={},{}local function O0l1Ol0(c)O0O0oO0[c]=true;O0O0O01[c]=coroutine.create(function()while O0O0oO0[c]do game:GetService("ReplicatedStorage").rEvents.openCrystalRemote:InvokeServer("openCrystal",c)O0O0O0O:Notify({Title="Egg Hatch",Content="Hatched "..c.."!",Duration=2})wait(.5)end end)coroutine.resume(O0O0O01[c])end;local function lO0O1O0(c)O0O0oO0[c]=false end;local oO0O0O0=false;local lO0Ol0I
Il1lI0O:CreateToggle({Name="Hatch Selected Crystal (On/Off)",CurrentValue=false,Callback=function(V)oO0O0O0=V;if V then lO0Ol0I=coroutine.create(function()while oO0O0O0 do game:GetService("ReplicatedStorage").rEvents.openCrystalRemote:InvokeServer("openCrystal",l1O1O0)O0O0O0O:Notify({Title="Egg Hatch",Content="Hatched "..l1O1O0.."!",Duration=2})wait(.5)end end)coroutine.resume(lO0Ol0I)end end})
Il1lI0O:CreateButton({Name="Hatch Selected Crystal (One Time)",Callback=function()game:GetService("ReplicatedStorage").rEvents.openCrystalRemote:InvokeServer("openCrystal",l1O1O0)O0O0O0O:Notify({Title="Egg Hatch",Content="Hatched "..l1O1O0.."!",Duration=2})end})
for _,c in ipairs(oollO0)do Il1lI0O:CreateToggle({Name=c.." (On/Off)",CurrentValue=false,Callback=function(V)if V then O0l1Ol0(c)else lO0O1O0(c)end end})end
OOo0O0O:CreateSection("Anti/Utility/Godmode Features")local O1O0O1O=16
OOo0O0O:CreateSlider({Name="WalkSpeed",Range={0,1000},Increment=1,Suffix="Speed",CurrentValue=O1O0O1O,Callback=function(V)local c=lO10l1O.Character;if c and c:FindFirstChild("Humanoid")then c.Humanoid.WalkSpeed=V end end})local l0O0lOl=false
OOo0O0O:CreateToggle({Name="Anti Knockback",CurrentValue=false,Callback=function(V)l0O0lOl=V;if l0O0lOl then spawn(function()while l0O0lOl do local c=lO10l1O.Character;if c then for _,a in pairs(c:GetDescendants())do if a:IsA("BodyVelocity")or a:IsA("BodyForce")or a:IsA("BodyAngularVelocity")or a:IsA("BodyThrust")or a:IsA("BodyGyro")then pcall(function()a:Destroy()end)end;if a:IsA("Humanoid")and a.PlatformStand then a.PlatformStand=false end end end;wait(.1)end end)end end})
local IlOlO1O=false;local o0l0O1O=nil;local l01lO1O=nil
OOo0O0O:CreateToggle({Name="Lock Position (Zero Movements, Full Anti-Teleport)",CurrentValue=false,Callback=function(V)IlOlO1O=V;if V then local c=lO10l1O.Character;if c and c:FindFirstChild("HumanoidRootPart")then o0l0O1O=c.HumanoidRootPart.CFrame end;l01lO1O=coroutine.create(function()while IlOlO1O do local c=lO10l1O.Character;if c and c:FindFirstChild("HumanoidRootPart")and c:FindFirstChild("Humanoid")then local h=c.HumanoidRootPart;local m=c.Humanoid;if(h.CFrame.Position-o0l0O1O.Position).Magnitude>.1 then h.CFrame=o0l0O1O end;m.WalkSpeed=0;m.JumpPower=0;h.Velocity=Vector3.new(0,0,0)h.RotVelocity=Vector3.new(0,0,0)m.PlatformStand=false end;wait(.05)end end)coroutine.resume(l01lO1O)end;if not V then local c=lO10l1O.Character;if c and c:FindFirstChild("Humanoid")then local m=c.Humanoid;m.WalkSpeed=O1O0O1O;m.JumpPower=50 end end end})local l0ll0l0=false
OOo0O0O:CreateToggle({Name="Anti-Teleport On Rebirth (BETA)",CurrentValue=false,Callback=function(V)l0ll0l0=V;if l0ll0l0 then spawn(function()local k=0;while l0ll0l0 do local s=lO10l1O:FindFirstChild("leaderstats")local x=s and s:FindFirstChild("Rebirths")if x then if k~=0 and x.Value>k then local c=lO10l1O.Character;if c and c:FindFirstChild("HumanoidRootPart")and o0l0O1O then wait(.5)c.HumanoidRootPart.CFrame=o0l0O1O end end;k=x.Value end;wait(.2)end end)end end})
local OlO0l0l=false
OOo0O0O:CreateToggle({Name="Anti AFK",CurrentValue=false,Callback=function(V)OlO0l0l=V;if OlO0l0l then if lO10l1O and lO10l1O.Idled then lO10l1O.Idled:Connect(function()if OlO0l0l then local VU=game:GetService("VirtualUser")VU:ClickButton2(Vector2.new())end end)end end end})local O0l0O0O=false
OOo0O0O:CreateToggle({Name="GODMODE (Can't be damaged)",CurrentValue=false,Callback=function(V)O0l0O0O=V;if O0l0O0O then spawn(function()while O0l0O0O do local c=lO10l1O.Character;if c and c:FindFirstChild("Humanoid")then local m=c.Humanoid;if m.Health<m.MaxHealth then m.Health=m.MaxHealth end;if m:GetState()==Enum.HumanoidStateType.Dead then m.Health=m.MaxHealth end;m.PlatformStand=false;if c:FindFirstChild("BreakJointsOnDeath")then pcall(function()c.BreakJointsOnDeath:Destroy()end)end;for _,a in pairs(c:GetDescendants())do if a:IsA("Explosion")or a:IsA("Fire")or a:IsA("Smoke")then pcall(function()a:Destroy()end)end end end;wait(.05)end end)end end})
O01Il1I:CreateSection("Evil Karma Magnet (RemoteEvent)")function isPlayerNameWhitelisted(n)return false end;function isUserIdWhitelisted(u)return false end
O01Il1I:CreateToggle({Name="Magnet Evil Karma to Right Hand & Punch (RemoteEvent)",CurrentValue=false,Callback=function(V)_G.AutoKillAllEvilKarma=V;task.spawn(function()local pos=nil;if lO10l1O.Character and lO10l1O.Character:FindFirstChild("HumanoidRootPart")then pos=lO10l1O.Character.HumanoidRootPart.CFrame end;while _G.AutoKillAllEvilKarma do local w=lO10l1O.Backpack:FindFirstChild("Punch")if w and not(lO10l1O.Character and lO10l1O.Character:FindFirstChild("Punch"))then lO10l1O.Character.Humanoid:EquipTool(w)task.wait(.1)end;for _,t in pairs(game.Players:GetPlayers())do if t~=lO10l1O and t.Character and t.Character:FindFirstChild("HumanoidRootPart")and lO10l1O.Character and lO10l1O.Character:FindFirstChild("RightHand")and not isPlayerNameWhitelisted(t.Name)and not isUserIdWhitelisted(t.UserId)then local s=false;for _,p in ipairs(t.Character:GetChildren())do if p.Name:lower():find("safe")then s=true;break end end;if not s then t.Character.HumanoidRootPart.CFrame=lO10l1O.Character.RightHand.CFrame*CFrame.new(0,0,-2)lO10l1O.muscleEvent:FireServer("punch","rightHand")local tool=lO10l1O.Character:FindFirstChild("Punch")if tool then tool:Activate()end end end end;if pos and lO10l1O.Character and lO10l1O.Character:FindFirstChild("HumanoidRootPart")then lO10l1O.Character.HumanoidRootPart.CFrame=pos end;task.wait(.2)end end)end})
l0l01lO:CreateButton({Name="Rejoin",Callback=function()local t=game:GetService("TeleportService")t:Teleport(game.PlaceId,lO10l1O)end})l0l01lO:CreateButton({Name="Legends gym",Callback=function()local c=lO10l1O.Character;if c and c:FindFirstChild("HumanoidRootPart")then c.HumanoidRootPart.CFrame=CFrame.new(4298.60059,1121.89404,-3898.68066)end end})l0l01lO:CreateButton({Name="Mythical gym",Callback=function()local c=lO10l1O.Character;if c and c:FindFirstChild("HumanoidRootPart")then c.HumanoidRootPart.CFrame=CFrame.new(2386.89038,139.607956,1094.26367)end end})l0l01lO:CreateButton({Name="Frost gym",Callback=function()local c=lO10l1O.Character;if c and c:FindFirstChild("HumanoidRootPart")then c.HumanoidRootPart.CFrame=CFrame.new(-2752.56543,125.822533,-386.73703)end end})l0l01lO:CreateButton({Name="Eternal gym",Callback=function()local c=lO10l1O.Character;if c and c:FindFirstChild("HumanoidRootPart")then c.HumanoidRootPart.CFrame=CFrame.new(-6917.79248,182.352829,-1336.63928)end end})l0l01lO:CreateButton({Name="Tiny island",Callback=function()local c=lO10l1O.Character;if c and c:FindFirstChild("HumanoidRootPart")then c.HumanoidRootPart.CFrame=CFrame.new(-4.25301933,220.993713,1963.60168)end end})l0l01lO:CreateButton({Name="Brawl aura 1",Callback=function()local c=lO10l1O.Character;if c and c:FindFirstChild("HumanoidRootPart")then c.HumanoidRootPart.CFrame=CFrame.new(985.910645,163.795364,-7037.80615)end end})l0l01lO:CreateButton({Name="Brawl aura 2",Callback=function()local c=lO10l1O.Character;if c and c:FindFirstChild("HumanoidRootPart")then c.HumanoidRootPart.CFrame=CFrame.new(4466.75342,334.973602,-8425.74512)end end})l0l01lO:CreateButton({Name="Brawl aura 3",Callback=function()local c=lO10l1O.Character;if c and c:FindFirstChild("HumanoidRootPart")then c.HumanoidRootPart.CFrame=CFrame.new(-1901.87695,251.895432,-5899.64795)end end})
I0O1lO1:CreateButton({Name="Set Day",Callback=function()game.Lighting.TimeOfDay="14:00:00"end,})I0O1lO1:CreateButton({Name="Set Night",Callback=function()game.Lighting.TimeOfDay="00:00:00"end,})I0O1lO1:CreateButton({Name="Set Morning",Callback=function()game.Lighting.TimeOfDay="07:00:00"end,})
l0O0lO1:CreateParagraph({Title="Note",Content="Made For RMPG"})l0O0lO1:CreateParagraph({Title="Second Note",Content="Made by Sen"})
local function destroyAll()for n,_ in pairs(O0Ol0O0)do O0Ol0O0[n]=false end;if getgenv().autoFarmRocks then for n,_ in pairs(getgenv().autoFarmRocks)do getgenv().autoFarmRocks[n]=false end end;_G.fastHitActive=false;for k,_ in pairs(lOl1I0O)do lOl1I0O[k]=false end;O0O1O1I=false;O1lO0O0=false;_G.AutoKillAllEvilKarma=false;_G.ManualAutoClick=false;_G.FarmTabAutoClick=false;_G.AutoPushupsJungleSquat=false;if game.CoreGui:FindFirstChild("Rayfield")then game.CoreGui.Rayfield:Destroy()end end
l0O0lO1:CreateButton({Name="Destroy GUI",Callback=function()destroyAll()end,})
